config/routes.rb
Myrottenpotatoes::Application.routes.draw do
  resources :my_tabels
  resources :movies
  root :to =>	redirect('/movies')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie	< ActiveRecord::Base
	def create
		Movi.create(movie_param)
	end
	
	private
	def movie_param
		params.require(:movi).permit(:title, :rating, :description, :release_date)
	end
end

app/models/my_tabel.rb
class MyTabel < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end


 def show
   id = params[:id] # retrieve movie ID from URI route
   @movie = Movie.find(id) # look up movie by unique ID
   # will render app/views/movies/show.html.haml by default
 end
 
 def new	
 #	default:	render	’new’	template	
 end

 def create
   @movie = Movie.create!(movie_param)	
   redirect_to movies_path
 end

 def movie_param
   params.require(:movie).permit(:title, :rating, :description, :release_date)
 end
 
 def edit
  @movie = Movie.find params[:id]
 end
 
 def update
  @movie = Movie.find params[:id]
  @movie.update_attributes!(movie_param)
  flash[:notice] = "#{@movie.title} was successfully updated."
  redirect_to movie_path(@movie)
 end
 
 def destroy
  @movie = Movie.find(params[:id])
  @movie.destroy
  flash[:notice] = "Movie '#{@movie.title}' deleted."
  redirect_to movies_path
end
 
end

app/controllers/my_tabels_controller.rb
class MyTabelsController < ApplicationController
  before_action :set_my_tabel, only: [:show, :edit, :update, :destroy]

  # GET /my_tabels
  # GET /my_tabels.json
  def index
    @my_tabels = MyTabel.all
  end

  # GET /my_tabels/1
  # GET /my_tabels/1.json
  def show
  end

  # GET /my_tabels/new
  def new
    @my_tabel = MyTabel.new
  end

  # GET /my_tabels/1/edit
  def edit
  end

  # POST /my_tabels
  # POST /my_tabels.json
  def create
    @my_tabel = MyTabel.new(my_tabel_params)

    respond_to do |format|
      if @my_tabel.save
        format.html { redirect_to @my_tabel, notice: 'My tabel was successfully created.' }
        format.json { render :show, status: :created, location: @my_tabel }
      else
        format.html { render :new }
        format.json { render json: @my_tabel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_tabels/1
  # PATCH/PUT /my_tabels/1.json
  def update
    respond_to do |format|
      if @my_tabel.update(my_tabel_params)
        format.html { redirect_to @my_tabel, notice: 'My tabel was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_tabel }
      else
        format.html { render :edit }
        format.json { render json: @my_tabel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_tabels/1
  # DELETE /my_tabels/1.json
  def destroy
    @my_tabel.destroy
    respond_to do |format|
      format.html { redirect_to my_tabels_url, notice: 'My tabel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_tabel
      @my_tabel = MyTabel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_tabel_params
      params.require(:my_tabel).permit(:nume, :altceva, :cv)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # user shouldn't have to be logged in before logging in!
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root, notice: 'Signed in'
  end
end

app/controllers/users_controller.rb
class UserController < ApplicationController

  def index
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_tabels_helper.rb
module MyTabelsHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %title RottenPotatoes!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
 
  %body
  = yield

app/views/movies/edit.html.haml
%h2 Edit Movie
 
= form_tag movie_path(@movie), :method => :put do
 
  = label :movie, :title, 'Title'
  = text_field :movie, 'title'
 
  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']
 
  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date
 
  = submit_tag 'Save Changes'

app/views/movies/index.html.haml
-#		This	file	is	app/views/movies/index.html.haml
%h1 All Movies
 
%table#movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Release Date
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)
= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
%h2 Create New Movie
 
= form_tag movies_path, :method => :post do
 
  = label :movie, :title, 'Title'
  = text_field :movie, :title
 
  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']
 
  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date
 
  = submit_tag 'Save Changes'

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml
 
%h2 Details about #{@movie.title}
 
%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
  = @movie.release_date.strftime("%B %d, %Y")
 
%h3 Description:
 
%p#description= @movie.description
 
= link_to 'Back to movie list', movies_path
= link_to 'Edit info', edit_movie_path(@movie)
= link_to 'Back	to movie list',	movies_path
-# This Delete link will not really be a link, but a form:
= link_to 'Delete', movie_path(@movie), :method => :delete

app/views/my_tabels/_form.html.erb
<%= form_for(my_tabel) do |f| %>
  <% if my_tabel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_tabel.errors.count, "error") %> prohibited this my_tabel from being saved:</h2>

      <ul>
      <% my_tabel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nume %>
    <%= f.text_field :nume %>
  </div>

  <div class="field">
    <%= f.label :altceva %>
    <%= f.text_field :altceva %>
  </div>

  <div class="field">
    <%= f.label :cv %>
    <%= f.text_field :cv %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_tabels/edit.html.erb
<h1>Editing My Tabel</h1>

<%= render 'form', my_tabel: @my_tabel %>

<%= link_to 'Show', @my_tabel %> |
<%= link_to 'Back', my_tabels_path %>

app/views/my_tabels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Tabels</h1>

<table>
  <thead>
    <tr>
      <th>Nume</th>
      <th>Altceva</th>
      <th>Cv</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_tabels.each do |my_tabel| %>
      <tr>
        <td><%= my_tabel.nume %></td>
        <td><%= my_tabel.altceva %></td>
        <td><%= my_tabel.cv %></td>
        <td><%= link_to 'Show', my_tabel %></td>
        <td><%= link_to 'Edit', edit_my_tabel_path(my_tabel) %></td>
        <td><%= link_to 'Destroy', my_tabel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My Tabel', new_my_tabel_path %>

app/views/my_tabels/new.html.erb
<h1>New My Tabel</h1>

<%= render 'form', my_tabel: @my_tabel %>

<%= link_to 'Back', my_tabels_path %>

app/views/my_tabels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nume:</strong>
  <%= @my_tabel.nume %>
</p>

<p>
  <strong>Altceva:</strong>
  <%= @my_tabel.altceva %>
</p>

<p>
  <strong>Cv:</strong>
  <%= @my_tabel.cv %>
</p>

<%= link_to 'Edit', edit_my_tabel_path(@my_tabel) %> |
<%= link_to 'Back', my_tabels_path %>